name: confly
description: >
  Type-safe, hierarchical app configuration for Dart and Flutter,
  with multi-environment support.
version: 1.0.6
repository: https://github.com/salbani/confly
issue_tracker: https://github.com/salbani/confly/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ">=7.5.9 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  built_collection: ^5.1.1
  code_builder: ">=4.11.0 <5.0.0"
  collection: ^1.19.1
  confly_annotation: ^1.0.2
  path: ^1.9.1
  source_gen: ">=3.1.0 <5.0.0"
  yaml: ^3.1.3


dev_dependencies:
  test: ^1.25.6
  build_runner: ^2.6.0
